### ISSUE TITLE
Support for IR

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#3365]
This is the tracking issue for having full support for [solc's IR-based code generation](https://docs.soliditylang.org/en/latest/ir-breaking-changes.html#).

We have already released a beta version with some basic support under the `ir` npm tag. This version can be installed with `npm install hardhat@ir`.

There are some pending things before we can release this in a stable version of Hardhat:

- [ ] Reverts with a reason string sometimes are not correctly handled (see discussion in #2453). I'm not sure if this was fixed on the `ir` version or not.
- [ ] What are exactly the best settings to have `viaIR` enabled but not lose important information used by stack traces and error inferring? Can we enable those settings automatically or should users do it?
- [ ] `solidity-coverage` seems to have issues when `viaIR` is enabled (see for example [this comment](https://github.com/NomicFoundation/hardhat/issues/2724#issuecomment-1321024602)). It's not clear if this is a problem in Hardhat or in the coverage plugin, or in both. It might also be just a documentation issue.
- [ ] At some point the "contract too large" heuristic wasn't working (see #2115). I believe this is fixed in the `ir` version, but we should double-check.

**Comment by scotthconner** [comment]
The issue I'm having is my tests are now failing with viaIR: true, specifically the ones that check the revertedWith message. Which is a lot of them.

For now, I'm having to turn viaIR off. Help me help us get to the bottom of it!

**Comment by scotthconner** [comment]
Also, turns out that hardhat@ir doesn't work with my version of solidity-coverage:

pm ERR! While resolving: @nomicfoundation/hardhat-toolbox@1.0.2
npm ERR! Found: solidity-coverage@0.8.2
npm ERR! node_modules/solidity-coverage
npm ERR!   dev solidity-coverage@"^0.8.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer solidity-coverage@"^0.7.21" from @nomicfoundation/hardhat-toolbox@1.0.2
npm ERR! node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!   @nomicfoundation/hardhat-toolbox@"^1.0.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: solidity-coverage@0.7.22
npm ERR! node_modules/solidity-coverage
npm ERR!   peer solidity-coverage@"^0.7.21" from @nomicfoundation/hardhat-toolbox@1.0.2
npm ERR!   node_modules/@nomicfoundation/hardhat-toolbox
npm ERR!     @nomicfoundation/hardhat-toolbox@"^1.0.2" from the root project

**Comment by fvictorio** [comment]
> The issue I'm having is my tests are now failing with viaIR: true, specifically the ones that check the revertedWith message.

That's the first item in the checklist.

> Also, turns out that hardhat@ir doesn't work with my version of solidity-coverage:

That's a llimitation of npm when a peer dependency and a pre-release version are mixed. You might need to use `npm install --force` when installing the `hardhat@ir` beta version.

**Comment by scotthconner** [comment]
Yup, thanks. I did --force and that worked.

It also works when running npm hardhat test. But when running coverage I get stack too deep.

**Comment by jmendiola222** [comment]
Is there a timeline for this to be included in the main release? Now that it's mark as ready I mean

**Comment by fvictorio** [comment]
@jmendiola222 we want to release this ASAP. Hopefully this or next week; definitely January.

**Comment by fruiz08** [comment]
do you have any workaround to solve this issue? https://github.com/ethereum/solidity/issues/13858

**Comment by fvictorio** [comment]
@fruiz08 that seems a solc thing, unrelated to Hardhat.

**Comment by hantuzun** [comment]
With IR, I get the following exception:

**Comment by hantuzun** [comment]
With IR, I get the following exception:

```
AssertionError: Expected transaction to be reverted with ABC, but other
exception was thrown: ProviderError: Error: Transaction reverted: function
was called with incorrect parameters
```

from a function as simple as:

```
function f() public {
  revert("ABC");
}
```

When IR is not used, or other parts of the contracts are tinkered, or YUL steps are tinkered, the issue resolves. This issue is very similar to https://github.com/NomicFoundation/hardhat/issues/2453 so I suspect it's a Hardhat issue.

I tried many combinations of recent Solidity versions with Hardhat `2.12.6` and `2.12.1-ir.0`. My compiler settings are:
```
viaIR: true,
optimizer: {
  enabled: true,
  runs: 200
}
```

Currently working around the issue with a custom order of YUL optimization steps.

Let me know if you think if this's a Solidity issue.

**Comment by hantuzun** [comment]
This's the stack trace from Hardhat `2.12.6`:

```
eth_estimateGas
  Error: Transaction reverted: function was called with incorrect parameters
      at Contract.f
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:429:7)
      at async HardhatNetworkProvider._sendWithLogging (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at async JsonRpcHandler._handleRequest (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at async JsonRpcHandler._handleSingleRequest (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at async Server.JsonRpcHandler.handleHttp (node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

**Comment by jmendiola222** [comment]
> @jmendiola222 we want to release this ASAP. Hopefully this or next week; definitely January.

It didn't make it to the last release. :( Any update on the plan? @fvictorio

**Comment by fvictorio** [comment]
I'm planning on merging that PR today, so it will definitely be included in the next release (this time for real :sweat_smile:).

**Comment by codeTIT4N** [comment]
is this fixed?

**Comment by fvictorio** [comment]
Released in [Hardhat v2.13.0](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.13.0) :rocket:

**Comment by thedavidmeister** [comment]
this warning when running tests

```
Your solidity settings have viaIR enabled, which is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.
```

and losing information about error strings

```
AssertionError: error string Error: Transaction reverted and Hardhat couldn't infer the reason.
```

with 2.13.0
