### ISSUE TITLE
hardhat-viem

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#4263]
Implement a first version of the `hardhat-viem` plugin. This will include:

- [x] https://github.com/NomicFoundation/hardhat/issues/4273
- [x] https://github.com/NomicFoundation/hardhat/issues/4274
- [x] https://github.com/NomicFoundation/hardhat/issues/4275
- [x] https://github.com/NomicFoundation/hardhat/issues/4276
- [ ] Release

**Comment by fvictorio** [comment]
This was released [today](https://medium.com/nomic-foundation-blog/hardhat-viem-808a536dcfe6) :tada:
