### ISSUE TITLE
Use Cancun by default

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#4851]
We'll do this after Cancun is enabled in mainnet.

**To-do**:
- [x] Use Cancun as the default hardfork in the Hardhat network config
- [x] Remove the code that skips Cancun in the `test/.../default-config.ts` test
- [x] Add the proper entry to the mainnet hardfork history in `src/.../default-config.ts`
- [x] Uncomment the Cancun-related tests in `forking-different-hardforks.ts`
    - [x] Add the cancun block number
    - [x] Update the values used in the tests (those are the ones that I used for sepolia, so they will be wrong for mainnet)
    - [x] Add tests for the beacon root contract

**Comment by cameel** [comment]
Are you seeing any CI failures with EVM version set to cancun? In Solidity we noticed Hardhat test suite failing with the latest version of the compiler when we switched to `cancun` by default (which we want to do in a release that will concide with Cancun activation on mainnet).

We're not sure if it's just some bit needed for full Cancun support still missing in Hardhat or maybe one of the still unreleased changes in solc that triggers this (the IR codegen starting to use `mcopy` for copying memory is one suspect).

The change also results in massive failures in other external projects we have hooked into CI via Hardhat, like OpenZeppelin.

@matheusaaguiar will soon open issues with more details and repros, but you can see the breakage in the failing jobs of https://github.com/ethereum/solidity/pull/14907 (all the `_ext_` ones).

**Comment by fvictorio** [comment]
For the record, this is about setting Cancun as the default hardfork of the Hardhat network. We are not going to use it as the default solc target for a while (we are not even using Shanghai as the default solc target yet).

But of course, things should work when Cancun is used as solc's target, so we are going to look into that. Thanks for letting us know!

**Comment by cameel** [comment]
An update on the problems on our side. Turns out it actually *is* related to the default hardfork setting. We only now realized that this setting is completely independent of the EVM version for the compiler and does not default to it. Perhaps it would be a good idea to make it so. In any case, setting it explicitly will probably solve our problem with the external projects we test.

**Comment by fvictorio** [comment]
> Perhaps it would be a good idea to make it so.

We had to be conservative after Shanghai, because people could accidentally deploy contracts with `PUSH0` in networks that didn't support it yet. It's not a great solution though; I hope we can do something smarter in future versions.

**Comment by r0qs** [comment]
Hey @fvictorio you might also consider changing this hardcoded setting: https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts#L34 to `cancun` when switching to it by default. I'm not sure if this is already on your radar, but it's the setting that resolved the failing stack tracing tests for us.
