### ISSUE TITLE
Refactor to utility package

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5060]
Create a utility package that abstracts some of our use of Node APIs in Hardhat.

We have not explicit goal to support alternate javascript runtimes (i.e. bun, deno), but as we move through HHv3 next work it would be useful to be explicit in our usage of Node APIs.

This refactor should be pragmatic - lets remove the low hanging fruit, and take the rest case by case.

Isolating Node APIs or depenedencies that leverage should help us be more intentional in our dependencies.

This work should be based off of the `Hardhat v3` branch.

## TODO

- [x] Create a new `utils` package meeting the Hardhat v3 conventions
- [x] Analyze usage of `fs` across the codebase, attempt to pull into utils package
- [x] Analyze usage of `fs-extra`, attempt to drop dependency, pull into utils package otherwise
- [x] Analyze usage of `glob`, attempt to drop dependency, pull into utils package otherwise
- [x] Analyze usage of `undici`, pull into utils package
- [x] Determine other potential dependencies that this approach would work for

**Comment by alcuadrado** [comment]
A good way to think about this is: hardhat core should not install `@types/node`.
