### ISSUE TITLE
Refactor Build System

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5109]
As part of the Hardhat v3 work we want to make the build system a top level component. Currently it is expressed as a collection of tasks. Our intent is to convert it into a standard component outwith the task subsystem, that will be provide a small number of hook in points that can be leveraged from a `compile` task.

## TODO

- [x] Move the build tasks into their own folder within core at the top level
- [x] Mirror that move for the compilation and build based tests
- [ ] Refactor the build system to be standard code rather than tests
