### ISSUE TITLE
Build system package cleanup

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5227]
The build system package is now in v-next. It will be hooked into the task system and cli in the future. This issue is to capture cleanup tasks we are aware over:

## TODO

- [ ] Use `hardhat-errors` over the errors in `hardhat-build-system` (same for `assertHardhatInvariant`)
- [ ] Assess and replace `hardhat-build-system` utils with `hardhat-utils`, cleanup the deps appropriately
- [ ] Restructure code along `public` / `internal` folder structure

**Comment by schaable** [comment]
Closed by https://github.com/NomicFoundation/hardhat/pull/5460
