### ISSUE TITLE
Core tasks missing features

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5229]
The tasks part of `./v-next/core` needs functionality filled out around the building up of task definitions and running the tasks.

## TODO

- [x] Complete the implementation of and test the TaskDefinition builders
- [x] Implement and test the ResolvedTask#run method, which runs the tasks
- [x] Polish and test the TaskManager
- [x] #5302
- [x] #5303
- [x] #5304
- [x] #5333
- [x] #5335
- [x] Check for missing dependencies using `detectPluginNpmDependencyProblems` in the `ResolvedTask#run` method when failing to import a file action.
