### ISSUE TITLE
Dependency tracking metric

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5366]
We have put significant effort into reducing and clarifying our dependencies in `v-next`. To build on this effort we should establish a metric or mechanism for measuring the number and size of our dependencies that we can use to benchmark the dependencies as the project progresses.

## Possible approach

Create a script that runs a clean install of the `v-next` Hardhat cli package and then counts the number of packages in the dependency tree and the size on disk of those dependencies.

## TODO

- [x] Investigate best practices, does anyone else do this and how do they do it
- [x] Put together a design doc in notion (https://www.notion.so/nomicfoundation/Hardhat-Dependency-Tracking-4da1bbd17a7443b7a2ab9f9da1931903?pvs=4)
- [x] Implement the process
- [x] Include in the `v-next` CI

**Comment by alcuadrado** [comment]
My initial proposal of things to track:

1. Number of dependencies in an empty hardhat installation
2. Number of dependencies in a default installation of hardhat (i.e. with the toolbox)

**Comment by galargh** [comment]
I put together a design doc for this as per the description - https://www.notion.so/nomicfoundation/Hardhat-Dependency-Tracking-4da1bbd17a7443b7a2ab9f9da1931903?pvs=4

The solution I proposed is already implemented at https://github.com/NomicFoundation/hardhat/pull/5653 because it came together as I explored the problem space. Of course, we can go in a different direction if the design discussion takes us elsewhere.
