### ISSUE TITLE
Integration testing with Node Test Runner

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5534]
Add integration testing support to Hardhat v3 based on Node Test Runner.

Node Test Runner support will be implemented as a separate package and plugin. It will add a `hardhat test` task that will initialize the `hre` and then execute the test suites, injecting the HRE into the context. 

Full details can be find in the [design doc](https://www.notion.so/nomicfoundation/Node-Test-Runner-Design-Doc-0aab6afb06814d2bb2fc5e299c00f77c?pvs=4).

## TODO

- [ ]  Add a new `@ignored/hardhat-node-test-runner` package under `./v-next`
- [ ]  Implement as a plugin task shim code similar to v2 mocha, that runs the designated test folder js/ts files as tests in Node test runner. Before the tests are run the HRE should be initialized and injected into the context.
- [ ]  Include the Hardhat custom test reporter in the default execution
- [ ]  Add `@ignored/hardhat-node-test-runner` to the example project and add some basic integration tests confirming that testing works and that the hre is being initialized
- [ ]  Add support for `--only` to the `npx hardhat test` command

## Out of Scope

- Coverage
- Gas reporting
- Parallel test execution
- Support for console.log in tests
