### ISSUE TITLE
Move to Hardhat repo

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5631]
Move Ignition to the Hardhat repo.

We still need to decide how to deal with existing issues and PRs in the Ignition repo.

We want to port the code in such a way that we can keep the commit history.

**Comment by kanej** [comment]
We have follow on tasks but the move into the Hardhat repo main branch is complete:

## TODO

- [ ] Ensure Hardhat Ignition packages are deployable from within the Hardhat repo
- [ ] Refactor hardhat-toolbox and the viem toolbox to use the workspace versions of Ignition
- [ ] Enable hardhat-ignition-examples

These will be added to the Ignition Hardhat 3 epic.
