### ISSUE TITLE
Documentation for v3

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5652]
Update the Hardhat website documentation to reflect the new features and changes in the Hardhat v3 release.

**Comment by alcuadrado** [comment]
Pasting this TODO here, I'll polish it tomorrow:

- [ ] Update the list of plugins
- [ ] Update Ignition docs to v3
- [ ] Update the doc of hardhat-network-helpers
- [ ] Update the top banner
- [ ] Create new top-level sections — Or what do we do now that everything is a plugin?
  - [ ] hardhat-ethers-chai-matchers
  - [ ] hardhat-viem-assertions
