### ISSUE TITLE
Setup Sentry and Google Analytics for Public Alpha

### ISSUE THREAD

**Issue by ChristopherDedominici** [NomicFoundation/hardhat#5657]
For the Hardhat 3 Public Alpha we are creating a new Sentry project.

replace TEST values with PROD values in Sentry and Analytics

Update the telemetry to point at production rather than the test environments for both:

* google analytics
* sentry

We should also double check 'flush' Sentry method before going to production

## TODO

- [x] replace TEST values with PROD values in Google Analytics - confirm with @alcuadrado 
- [x] Create a new Sentry project specifically for Hardhat 3 and update Hardhat 3 to point at it
- [x] Set up alerting to Slack
  * Only Sentry team admins/moderators can set up alerts and I am not one.
  * The alerting rule should be added here: https://nomic-labs.sentry.io/alerts/rules/?project=4507685793103872&statsPeriod=1h&utc=true
  * It should be similar to the one we have configured for Hardhat v2: https://nomic-labs.sentry.io/alerts/rules/buidler/1079337/details/ 
- [ ] Manual confirmation that reporting is coming through for both Sentry and Google Analytics

**Comment by galargh** [comment]
Pato set up https://nomic-labs.sentry.io/projects/hardhat3/?project=4508780138856448 and alerting for it to #hardhat3-sentry

**Comment by galargh** [comment]
I put together https://github.com/NomicFoundation/hardhat/pull/6251 which updates the Sentry DSN. I'm waiting to gain access to Google Analytics.

**Comment by kanej** [comment]
I have moved the reporter flushing task out to its own issue in the Public Alpha Rollout milestone:

https://github.com/NomicFoundation/hardhat/issues/6275

**Comment by alcuadrado** [comment]
I just validated this again with the published packages
