### ISSUE TITLE
hardhat --init cleanup

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5954]
The Hardhat v3 alpha includes `--init` support. Testing for alpha has shown we need some follow up tasks.

## TODO

- [ ] Tests for installation of `--init`, this doesn't need to be e2e but it should test at a minimum it should prove that spawn works on different platforms.
- [ ] `--init` doesn’t show “help us improve…”
- [ ] `--init` doesn’t check for existing dependencies.
    - e.g. if you have `viem` already installed in the package, it just installs it again, potentially a different version
    - Maybe we should check this before even copying any file and fail
        - except for a hardhat clash, which will be common

**Comment by galargh** [comment]
One of the items listed in the original description wasn't directly related to `--init` so I moved it to a separate issue - https://github.com/NomicFoundation/hardhat/issues/5960
