### ISSUE TITLE
micro-eth-signer issue when deploying local accounts

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5967]
There was an issue with `micro-eth-signer` that has been fixed here: https://github.com/paulmillr/micro-eth-signer/releases/tag/0.12.2

Specifically it didn't allow a zero address when deploying a contract. Even with the fix `micro-eth-signer`, it doesn't support sending a transaction to the null address without data. As this is likely a user error we should throw in that situation.

## TODO

- [x] Update to the fixed version of `micro-eth-signer`
- [ ] Add tests to cover previous bug
- [x] Add a guard and tests to cover the case where the transaction address is null without data
