### ISSUE TITLE
Robustness improvements in the compiler downloader

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5990]
In Hardhat 3 the compiler downloader has been ported over. It is missing some key robustness features that Hardhat 2 had, and some features we wanted to add to Hardhat 2's version of the compiler downloader.

## TODO

- [x] Bring back mutex during multiple compiler downloads 
- [x] The downloader and compiler classes were imported but not their tests
- [x] The downloader was changed but not its tests
- [x] Always download both native and wasm builds
- [x] #6071
