### ISSUE TITLE
Build system testing

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5997]
For the initial alpha release we ported parts of the Hardhat 2 build system but not the matching tests. We need to port those across as well, and enhance them in the places we have made changes.

## TODO

- [x] solc config selection testing
- [x] root path utils testing
- [x] Dependency graph testing
- [x] Dependency graph building testing
- [x] Testing of artifacts generation and cleanup
